name: test bilibili
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s "https://rss.941009.xyz/bilibili/user/video/478715267" | head -c 2000
