name: test moegirl
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s "https://zh.moegirl.org.cn/api.php?action=query&list=recentchanges&rcnamespace=0&rclimit=10&format=json" | head -c 3000
